---

  - name: 创建hadoop组
    group: name=hadoop gid=2018 state=present system=yes
    ignore_errors: True
    register: result

  - name: 新建用户并获取root权限
    user: name=hadoop shell=/bin/bash groups=hadoop home=/usr/hadoop createhome=yes system=yes
    ignore_errors: True

  - name: 创建cdh文件夹
    file: path={{cdh_all_app_path}} group=hadoop owner=hadoop mode=0755 state=directory

  - name: 解压hadoop安装包
    unarchive: src={{hadoop_package_name}} dest={{cdh_all_app_path}}/

  - name: 更改hadoop文件名称
    shell: mv -f {{cdh_all_app_path}}/hadoop* {{cdh_all_app_path}}/hadoop

  - name: 修改文件的所有组、人、权限
    file: path={{cdh_all_app_path}}/hadoop recurse=Yes owner=hadoop group=hadoop mode=0755

  - name: 设置hadoop配置文件
    template: src={{item}} dest={{cdh_all_app_path}}/hadoop/etc/hadoop/{{item}} group=hadoop owner=hadoop mode=0755
    with_items:
    - core-site.xml
    - hdfs-site.xml
    - yarn-site.xml
    - mapred-site.xml
    - hadoop-metrics2.properties
    - log4j.properties
    - hadoop-env.sh
    - slaves

  - name: 设置环境变量/etc/profile.d/hadoop
    template: src=profile.j2 dest=/etc/profile.d/hadoop owner=root group=root mode=0644

  - name: 设置环境变量/root/.bashrc
    template: src=bashrc.j2 dest=/root/.bashrc owner=root group=root mode=0644

  - name: 使环境变量生效
    shell: source /etc/profile.d/hadoop

  - name: 使环境变量立即生效
    shell: source /root/.bashrc

  #适配cdh图形版和公版的通用性，主要为presto服务
  - name: 创建/etc/hadoop
    file: path=/etc/hadoop group=hadoop owner=hadoop mode=0755 state=directory

  - name: 将hadoop配置文件链接到/etc/hadoop
    file: src={{cdh_all_app_path}}/hadoop/etc/hadoop dest=/etc/ owner=hadoop group=hadoop mode=0755 state=link  force=yes
    ignore_errors: True