---

  - name: 检查文件是否存在
    shell: ls {{dmudb_tomcat_directory}}/tomcat
    ignore_errors: True
    register: result

  - name: 存在则停止服务
    shell: ps -ef | grep "{{dmudb_tomcat_directory}}/tomcat" | grep -v grep | tr -s " "|cut -d" " -f2 | xargs kill -9
    when: result|succeeded
    ignore_errors: True

  - name: 存在则删除原始文件
    shell: rm -rf {{dmudb_tomcat_directory}}/tomcat
    when: result|succeeded

  - name: 移除dmudb服务
    shell: chkconfig --del tomcat
    ignore_errors: True

  - name: 移除定时任务
    cron: name="start dmudb" minute={{cron_time}} hour=* day=* month=* weekday=* job="sh {{tmp_dir}}/dm_udb_crontab.sh" user=root state=absent
