---
  - name: 检查elasticsearch文件是否存在
    shell: ls {{cdh_all_app_path}}/elasticsearch
    ignore_errors: True
    register: result

  - name: 存在则删除elasticsearch文件
    file: path={{cdh_all_app_path}}/elasticsearch state=absent
    when: result|succeeded

  - name: 存在则杀掉es相关进程
    shell: ps -ef | grep elasticsearch | grep -v "grep" | awk '{print $2}'| xargs kill -9
    when: result|succeeded
    ignore_errors: True

  - name: 存在则杀掉es head相关进程
    shell: ps -ef | grep grunt | grep -v "grep" | awk '{print $2}'| xargs kill -9
    when: result|succeeded
    ignore_errors: True

  - name: 存在则杀掉kibana相关进程
    shell: ps -ef | grep kibana | grep -v "grep" | awk '{print $2}'| xargs kill -9
    when: result|succeeded
    ignore_errors: True

  - name: 存在则杀掉filebeat相关进程
    shell: ps -ef | grep filebeat | grep -v "grep" | awk '{print $2}'| xargs kill -9
    when: result|succeeded
    ignore_errors: True

  - name: 存在则删除相关软件
    yum: name={{item}} state=absent
    with_items:
      - elasticsearch
      - kibana
      - filebeat
    when: result|succeeded
    ignore_errors: True

  - name: 删除/usr/bin/java
    file: path=/usr/bin/java state=absent

  - name: 删除旧的es文件
    file: path=/etc/elasticsearch state=absent

  - name: 删除旧的gc日志文件
    file: path=/var/log/gc.log state=absent

  - name: 删除旧的kibana日志文件
    file: path=/var/log/kibana.log state=absent

  - name: chkconfig移除es head服务
    shell: chkconfig --del eshead
    ignore_errors: True

  - name: chkconfig移除kibana服务
    shell: chkconfig --del kibana
    ignore_errors: True

  - name: 移除定时任务
    cron: name="start es" minute={{cron_time}} hour=* day=* month=* weekday=* job="sh {{tmp_dir}}/es_crontab.sh" user=root state=absent
