---
  - name: 检查hbase文件是否存在
    shell: ls {{cdh_all_app_path}}/hbase
    ignore_errors: True
    register: result

  - name: 存在先停止hbase
    shell: sh stop-hbase.sh chdir={{cdh_all_app_path}}/hbase/bin/
    when: result|succeeded

  - name: 存在则删除hbase文件
    file: path={{cdh_all_app_path}}/hbase state=absent
    when: result|succeeded

  - name: 移除用户hbase
    user: name=hbase  state=absent
    ignore_errors: True

  - name: chkconfig移除hbase服务
    shell: chkconfig --del hbase
    ignore_errors: True

  - name: 移除定时任务
    cron: name="start hbase" minute={{cron_time}} hour=* day=* month=* weekday=* job="sh {{tmp_dir}}/hb_crontab.sh" user=root state=absent
