---
  - name: 检查hue文件是否存在
    shell: ls {{cdh_all_app_path}}/hue
    ignore_errors: True
    register: result

  - name: 存在则停止hue服务
    shell: ps -ef | grep hue | grep -v "grep" | awk '{print $2}'| xargs kill -9
    ignore_errors: True
    when: result|succeeded

  - name: 存在则删除hue文件
    file: path={{cdh_all_app_path}}/hue state=absent
    when: result|succeeded

  - name: 移除用户hue
    user: name=hue  state=absent
    ignore_errors: True

  - name: chkconfig移除hue服务
    shell: chkconfig --del hue
    ignore_errors: True

  - name: 移除定时任务
    cron: name="start hue" minute={{cron_time}} hour=* day=* month=* weekday=* job="sh {{tmp_dir}}/hu_crontab.sh" user=root state=absent
