---

  - name: 新建用户并获取root权限
    user: name=flume shell=/bin/bash groups=hadoop home=/usr/flume createhome=yes system=yes
    ignore_errors: True

  - name: 创建cdh文件夹
    file: path={{cdh_all_app_path}} group=hadoop owner=hadoop mode=0755 state=directory

  - name: 解压flume安装包
    unarchive: src={{flume_package_name}} dest={{cdh_all_app_path}}/

  - name: 更改flume文件名称
    shell: mv -f {{cdh_all_app_path}}/*flume* {{cdh_all_app_path}}/flume

  - name: 修改文件的所有组、人、权限
    file: path={{cdh_all_app_path}}/flume recurse=Yes  owner=flume group=hadoop mode=0755

  - name: 设置flume配置文件
    template: src={{item}} dest={{cdh_all_app_path}}/flume/conf/{{item}} owner=flume group=hadoop mode=0755
    with_items:
    - flume.conf
    - flume-env.sh
    - log4j.properties