---

  - name: 创建hadoop组
    group: name=hadoop gid=2018 state=present
    ignore_errors: True

  - name: 新建用户hbase并获取root权限
    user: name=hbase shell=/bin/bash groups=hadoop home=/usr/hbase createhome=yes system=yes
    ignore_errors: True

  - name: 创建cdh5文件夹
    file: path={{cdh_all_app_path}} state=directory

  - name: 解压hbase安装包
    unarchive: src={{hbase_package_name}} dest={{cdh_all_app_path}}/

  - name: 更改hbase文件名称
    shell: mv -f {{cdh_all_app_path}}/hbase* {{cdh_all_app_path}}/hbase

  - name: 修改文件的所有组、人、权限
    file: path={{cdh_all_app_path}}/hbase  recurse=Yes owner=hbase group=hadoop mode=0755

  - name: 设置hbase配置文件
    template: src={{item}} dest={{cdh_all_app_path}}/hbase/conf/{{item}} owner=hbase group=hadoop mode=0664
    with_items:
    - hbase-site.xml
    - hbase-env.sh
#    - backup-masters
    - regionservers
    - log4j.properties
    - hadoop-metrics2-hbase.properties

  - name: 拷贝mysql-connector-java-5.1.44.jar到hbase/lib下
    copy: src={{mysql_jdbc_jar}} dest={{cdh_all_app_path}}/hbase/lib/