---
######################################### es 服务 #########################################################################
  - name: 设置elasticsearch配置文件
    template: src=es_master.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0755

  - name: 启动es服务
    service: name=elasticsearch state=restarted enabled=yes

  - name: 等待1分钟
    pause: minutes=1

############################################ es head #########################################################################
  - name: 拷贝es head依赖包到{{cdh_all_app_path}}/elasticsearch/下
    copy: src=dept dest={{cdh_all_app_path}}/elasticsearch/

  - name: 安装es head依赖包
    shell: yum -y install * chdir={{cdh_all_app_path}}/elasticsearch/dept/
    ignore_errors: True

  - name: 解压es head安装包到{{cdh_all_app_path}}/elasticsearch/下
    unarchive: src={{es_head_name}} dest={{cdh_all_app_path}}/elasticsearch/

  - name: 设置es head配置文件Gruntfile.js
    template: src=Gruntfile.js.j2 dest={{cdh_all_app_path}}/elasticsearch/elasticsearch-head/Gruntfile.js owner=root group=root mode=0755

  - name: 设置es head配置文件app.js
    template: src=app.js.j2 dest={{cdh_all_app_path}}/elasticsearch/elasticsearch-head/_site/app.js owner=root group=root mode=0755

  - name: 启动es head服务
    shell: "nohup ./grunt server &  chdir={{cdh_all_app_path}}/elasticsearch/elasticsearch-head/node_modules/grunt/bin/"
    async: 10  #最长等待10秒返回
    poll: 0    #值为0表示无需等待该任务返回


  - name: 处理启动脚本grunt.sh.j2
    template: src=grunt.sh.j2 dest=/etc/init.d/eshead owner=root group=root mode=0777

  - name: chkconfig加入es head服务
    shell: chkconfig --add eshead

  - name: eshead开机自启动
    service: name=eshead state=restarted enabled=yes


######################################### kibana #########################################################################
  - name: 拷贝kibana rpm包到{{cdh_all_app_path}}/elasticsearch
    copy: src={{kibana_rpm_name}} dest={{cdh_all_app_path}}/elasticsearch/

  - name: 安装kibana rpm包
    shell: yum -y install {{kibana_rpm_name}} chdir={{cdh_all_app_path}}/elasticsearch/
    ignore_errors: True

  - name: 设置kibana配置文件
    template: src=kibana.yml.j2 dest=/etc/kibana/kibana.yml owner=root group=root mode=0755

  - name: 创建kibana日志文件
    file: path=/var/log/kibana.log state=touch owner=root group=root mode=0777

  - name: 启动kibana服务
    shell: nohup /etc/init.d/kibana restart &
    #service: name=kibana state=started enabled=yes

  - name: 自启动kibana服务
    #service: name=kibana state=started enabled=yes
    shell: chkconfig kibana on
    ignore_errors: True

  - name: 等待1分钟
    pause: minutes=1




################################################# 定时拉起 #######################################################################
  - name: 处理定时任务模板文件es_master_crontab.sh.j2
    template: src=es_master_crontab.sh.j2 dest={{tmp_dir}}/es_crontab.sh owner=root group=root mode=0777

  - name: 加入定时任务
    cron: name="start es" minute={{cron_time}} hour=* day=* month=* weekday=* job="sh {{tmp_dir}}/es_crontab.sh" user=root state=present
