---

  - name: 新建用户并获取root权限
    user: name=jstorm shell=/bin/bash groups=hadoop home=/usr/jstorm createhome=yes system=yes
    ignore_errors: True

  - name: 创建cdh文件夹
    file: path={{cdh_all_app_path}} group=hadoop owner=jstorm mode=0755 state=directory

  - name: 解压jstorm安装包
    unarchive: src={{jstorm_package_name}} dest={{cdh_all_app_path}}/

  - name: 更改jstorm文件名称
    shell: mv -f {{cdh_all_app_path}}/jstorm* {{cdh_all_app_path}}/jstorm

  - name: 更改jstorm ui文件名称
    shell: mv -f {{cdh_all_app_path}}/jstorm/jstorm-ui-*.war {{cdh_all_app_path}}/jstorm/jstorm.war

  - name: 修改文件的所有组、人、权限
    file: path={{cdh_all_app_path}}/jstorm recurse=Yes owner=jstorm group=hadoop mode=0755

  - name: 设置jstorm配置文件
    template: src=storm.yaml.j2 dest={{cdh_all_app_path}}/jstorm/conf/storm.yaml group=hadoop owner=jstorm mode=0755

  - name: 创建~/.jstorm
    file: path=~/.jstorm group=hadoop owner=jstorm mode=0755 state=directory

  - name: 设置jstorm配置文件
    template: src=storm.yaml.j2 dest=~/.jstorm/storm.yaml group=hadoop owner=jstorm mode=0755

  - name: 设置jstorm启动脚本
    template: src=start.sh.j2 dest={{cdh_all_app_path}}/jstorm/bin/start.sh group=hadoop owner=jstorm mode=0777

  - name: jstorm ui软链接到tomcat
    file: src={{cdh_all_app_path}}/jstorm/jstorm.war dest={{dmudb_tomcat_directory}}/tomcat/webapps/jstorm.war owner=root group=root mode=0777 state=link force=yes
    ignore_errors: True

  - name: 启动tomcat服务器
    service: name=tomcat state=restarted
    ignore_errors: True

  - name: 等待1分钟
    pause: minutes=1